# Numpy starting

it is the foundation of pandas, pytorch, tensorflow 

``` Vector    means 1d-array ```
example arr=[1,2,3,4]

```matrix  two or three```
example :[[1,2,4],[1,2,3,4]]

``` n dimensional array```
 example : [[[1,2,3],[1,2]],[[1,2,3],[1,2,3]]]

##### numpy written in c++ (hardware oriented fast)
- fast for similar datatype operations 


In [4]:
import numpy as np

### creating array from list

In [5]:
array_1d=np.array([1,2,3,4])
print(array_1d)

[1 2 3 4]


In [7]:
array_2d=np.array([[1,2,3,],[1,3,4]])
print(array_2d)

[[1 2 3]
 [1 3 4]]


List vs numpy array 

In [ ]:
list1 =[1,2,3]
print("python list multiplication ",list1*2)  #here  2 is constant multiplication 


array_list=np.array(list1)
print("python list multiplication ",array_list*2) #2 is  multiply by scalar , element wise multiplicaiton 


python list multiplication  [1, 2, 3, 1, 2, 3]
python list multiplication  [2 4 6]


In [9]:
import time 

start_time=time.time()
list2= [i*2 for i in range(100000)]
print("total time taken",time.time()-start_time)


start_time=time.time()
list2= np.arange(100000)*2
print("total time taken",time.time()-start_time)



total time taken 0.011087656021118164
total time taken 0.009536266326904297


### creating  array from scratch

In [11]:
zeroes=np.zeros((3,4))
print(zeroes)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [ ]:
ones=np.ones((2,3))
print("ones matrix",ones)

[[1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
# for constant value matrix
arr=np.full((2,3),7)
print('arr\n',arr)

arr [[7 7 7]
 [7 7 7]]
